FROM docker.io/golang:1.24-alpine AS builder

WORKDIR /build
COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY main.go .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /service-hub .

FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /service-hub /service-hub
ENTRYPOINT ["/service-hub"]
