name: Update Podman Images

on:
  pull_request:
    types: [closed]

jobs:
  update:
    if: forgejo.event.pull_request.merged == true && startsWith(forgejo.event.pull_request.head.ref, 'updates/')
    runs-on: host
    steps:
      - name: Pull latest changes and update images
        run: |
          cd ~/home-services
          git checkout main
          git pull origin main
          just update-podman-images
