name: Update Podman Images

on:
  pull_request:
    types: [closed]

jobs:
  update:
    if: forgejo.event.pull_request.merged == true && startsWith(forgejo.event.pull_request.head.ref, 'updates/')
    runs-on: host
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Sync quadlets and update images
        run: |
          just copy-quadlets
          systemctl --user daemon-reload
          just update-podman-images
