FROM fedora:44

RUN tee /etc/yum.repos.d/proton-drive-sync.repo << 'EOF'
[proton-drive-sync]
name=Proton Drive Sync
baseurl=https://repo.damianb.dev/yum/
enabled=1
gpgcheck=0
EOF

RUN dnf install -y proton-drive-sync-prerelease && dnf clean all
