FROM docker.io/library/fedora:44

ARG CACHEBUST=1
RUN echo "cachebust=$CACHEBUST"

RUN dnf install -y --setopt=install_weak_deps=False \
    just \
    git \
    podman \
    systemd \
    yq \
    wget \
    jq \
    nodejs \
    fish \
    && dnf clean all

RUN curl -sSL https://github.com/getsops/sops/releases/download/v3.13.3/sops-v3.13.3.linux.amd64 -o /usr/local/bin/sops && \
    chmod +x /usr/local/bin/sops
