log:
  level: info
  job_level: info

runner:
  file: /data/.runner
  capacity: 1
  timeout: 3h
  shutdown_timeout: 3h
  insecure: false
  fetch_timeout: 5s
  fetch_interval: 2s
  envs:
    CONTAINER_HOST: unix:///var/run/docker.sock
    XDG_RUNTIME_DIR: /run/user/1000
    HOME: /home/lgomes
  labels:
    - "host:docker://localhost/forgejo-runner-job:latest"

cache:
  enabled: false

container:
  network: ""
  enable_ipv6: false
  privileged: false
  docker_host: "unix:///run/user/1000/podman/podman.sock"
  options: "-v /run/user/1000/systemd/private:/run/user/1000/systemd/private -v /home/lgomes/.config/containers/systemd:/home/lgomes/.config/containers/systemd:Z -v /home/lgomes/.config/systemd/user:/home/lgomes/.config/systemd/user:Z"

host:
  workdir_parent: /tmp

server:
  connections:
    default:
      url: https://git.lgomes.net
      fetch_interval: 30s
