log:
    level: ENC[AES256_GCM,data:9aTH1Q==,iv:UdbFtPkWidZ2qOB30bDLLmRnNSMhGPwMmOAgAny7WCk=,tag:P9xBrLHTW5UmRX7Iu/OsjQ==,type:str]
    job_level: ENC[AES256_GCM,data:6BhjNA==,iv:M0eLVRalai5b3XNAlDg/DpuyPmG8KryK+dKQsZyXSCg=,tag:FRK9HhU2LlRMWMbtfMJXfw==,type:str]
runner:
    file: ENC[AES256_GCM,data:Rv71dYYZnduZ4ndFkA==,iv:vhQeumBnlyrPnzfVZKm9p2z7K0eiPad1BRxxPiXe+XY=,tag:Z/gF5cN5TcRi1nFRkfO0OQ==,type:str]
    capacity: ENC[AES256_GCM,data:zQ==,iv:DGbzKV0uqnX4LgNsf4jNhzCb3x+BKMkWqVDptiEzsjI=,tag:u2jBnpBpZYiqPBoiegmL1g==,type:int]
    timeout: ENC[AES256_GCM,data:JnI=,iv:8frPFelGHOxSJxxk2/WcBVjbVAYl2KLT68IBpyGYcG8=,tag:9nj/sBmpJWZQCmNgGFIqnQ==,type:str]
    shutdown_timeout: ENC[AES256_GCM,data:me4=,iv:uQA2acC4l+ebDX0ecnbXVwjU3uVEGnd9Nn0Mfr1AgAk=,tag:WZ5xlAc+oD0KfF/bZeYMwQ==,type:str]
    insecure: ENC[AES256_GCM,data:+1AjNnc=,iv:XsKRkTuLNRlRUOyAEB9DhFkVN6M5em+N0E8y4BA24Fo=,tag:MLO9beZ6cANjgKsXbainsg==,type:bool]
    fetch_timeout: ENC[AES256_GCM,data:YZU=,iv:N7Pt1yf2CtnyccvwRR2cT/RwZdGFe9B0UnFCAZctdu4=,tag:0ptqXmpSaUYwy4PqiwrEfQ==,type:str]
    fetch_interval: ENC[AES256_GCM,data:PSY=,iv:Vu9wZ9TaJIVs4mw4VjzsKbwMep55wDBtNTNBYtUzRIo=,tag:qj7a4nC7VZaZQNBSHx7diw==,type:str]
    envs:
        CONTAINER_HOST: ENC[AES256_GCM,data:uTIZ4RSTCdXTdkjNN0nBR4G2ZCgcpSjwWE20,iv:kCXlnBpIPNWgcp5DcyIXP1AXvHSbC1R9MqtfK6KTAHY=,tag:DXVriszZBENT/kYgfX2BzA==,type:str]
        SOPS_AGE_KEY: ENC[AES256_GCM,data:4EMjBXFKKWzDUZLw8wwTn9zqv0yWAzKyBqm0lIfvdXhcExKthyaUfue7NrPc4aLcEshBWSiwssVA0QseWizP99QqFO5sEvqWUbD3I/WeLuzNdr3K1l4/PaLWeXGFPzU1lVXAd7IV8pPfeFYxfvWlspzVgJjUHC8/TXjzhSIVHxOADs/349d9p9cQ1uCnMumdHiuVQ26pxweVfr6Wiw+vAD/xx0NVbYrBZAfoH3T/9E5HLiHZE+5W,iv:NrOc2jpoJEH2YuIxRQXZqBZDbXbwHhSPfHieJUhC2xw=,tag:H9TTN82gGPfN9R0ZBvcr3Q==,type:str]
    labels:
        - ENC[AES256_GCM,data:xhnAcDlVbui0s54MzB/RlvA6rXDV/DZvdfW0bLiRNmS9aFLMyJqQsw1TuQmnF5Xm6g==,iv:ueLRnk9h0ffSaA3J7EDy4oRRcZIyMHlErKSnPjOju24=,tag:ZI8A1H0lGTmsnfXFNQbHGA==,type:str]
cache:
    enabled: ENC[AES256_GCM,data:xdEjDHQ=,iv:A2XZX3VMQK3p9IGVWZcczekPM0MoLWpMwJwlLgqNFFQ=,tag:PcCsyNYw3d+yEXJhgR5dPg==,type:bool]
container:
    network: ""
    enable_ipv6: ENC[AES256_GCM,data:WX5dZjs=,iv:VHuOA/hRyve7hOGqe64wusrBvpeE0jkqvSUvpUEHbmo=,tag:iBJaM+1bRZSCcm3Fg6mnsw==,type:bool]
    privileged: ENC[AES256_GCM,data:x5Hl7NI=,iv:4OcAdY+FXu6tcXPBQI5OvpR7eusgM63cqdsm5xD6EFM=,tag:kwoxRkoGdSO3vDSJLAy2IQ==,type:bool]
    docker_host: ENC[AES256_GCM,data:+uboeLecL71O0qvG6PLuMygsDBPlTSASHJkpQXVa7PKldOQegtZjWQ==,iv:ke0qOSlCq8joSjOWD0ftb4DpICY4yW0XZNMMyMtnQyo=,tag:PynPrpRpfeFZdjNmHQpy8w==,type:str]
    options: ENC[AES256_GCM,data:p5W7IXMMTtcmzEIeOTkOGMKjsVj+pJDKEBwj3gSNAts8Eg5539cSmTl7XE7Z3388wqzJt3V5DU4sQe8Ngy1t1iMToJ2PkptR4EMEJsnjPjcOSpMSf8wfSZE2b6er44XJdMjmChhsDcigbkJiaEh3fBQMy5KB/bnzPokjQqLY+p2dYseEyCR/L9d43yU7+Ia8RiL3LD1Ou3CHCID9cGQd3RnTXcDv02VTemAj+Lc1XHg85ETgH6/TxQIUhbw+Uo+L64endYq9Ef/EeF1u,iv:UNTUCfxkrUD8qq4HuxIyu5XjOxn3aobgHxi/JuikoS0=,tag:4wyfGXqTDsQC433t/tgocw==,type:str]
    valid_volumes:
        - ENC[AES256_GCM,data:RVhH0HN2LUZ4BB2yVyLKSUMpafByD+aYL41Vd5Kf,iv:yAEn2rFv4RD/Ido2GSJWZthz/xBgessrXkZVQzLNHNE=,tag:4g1JuMIxFfH6oNZGDan3QA==,type:str]
        - ENC[AES256_GCM,data:BtelUWGwBRsQs1xTfh3dRJ0q2uVe/e9ITS1mCpDxPdaEothtFLro,iv:WL4uqT4FndNFaQxak9pweVia2Qd8ldhLlNUP0tlHm9w=,tag:TwyWh19oZ2IsITGbMKM0GQ==,type:str]
        - ENC[AES256_GCM,data:CdUriPc/cUyJsXTnjBRmtywM/fgLbvwBlYMLqhyYsh8R,iv:/T2r8PONIAPZeY3i9Ui0HMyVujICruO6o4z7RTHXNq4=,tag:Qn5YijMaqAkyiCL66yEr0g==,type:str]
host:
    workdir_parent: ENC[AES256_GCM,data:k0Njdg==,iv:P13x8mtqSeVZDcaSg+6X6C7urXmhhn+isDuQF+7aU24=,tag:86lzPaCEg8f5CgYN4Ods8g==,type:str]
server:
    connections:
        forgejo:
            url: ENC[AES256_GCM,data:H1hfkheKTDSZbJNfAOvj4ZtsBzrYLtkPXIw=,iv:6DK3aHwTGt151TIR/SfvsNYzpUQlDqG5zeQKQThnLWI=,tag:ZrM3jx61mJ0QUOua7686Zw==,type:str]
            uuid: ENC[AES256_GCM,data:pJ9YyPKBf+Y5LstPv2egr2rCJfH6/veHAqhFdoliRta9y4wk,iv:3RaWarjSTm3xOfjGersggvHE5p5XwVWi6lqJEVtB1gQ=,tag:5Pck3DFbTmj2oGssxU6ivQ==,type:str]
            token: ENC[AES256_GCM,data:/LmtNwkzVjByV5NPPpm0U5h1x3WGZDY/qZsNURRZahP+cCouzb6oKQ==,iv:82OdNOUX1+Pao2JtVrFqCf1Zd8cZreN7b7E4g89QRBI=,tag:ng4/n8erq3SdKkX2npxg6Q==,type:str]
sops:
    age:
        - recipient: age197damvmzfln6huddgr6ujg8qjnmphsv5rumdu5xfh7c69dvsadasdpvce7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSk0xUmlBdjBxL1B1ODNX
            MHVSeXJvNVhKUlA1NjdVRzR0cEJYcFdYdEFjCmtPRUQzaHBYOUJXN0k4aGxicjRW
            SmxTM2ovazFuL3VHMTlIZ2FnUExzSkkKLS0tIGdSZ1hzVzZrditJMW9BbGNrR1JQ
            OTJ5ZCtjeTJ5V2IvZytQUVVvS1JyNnMKjPUlanCJpfX8TpbtdMVpQmTAS8daDWlR
            GmlnFqXLbM2e4J3urarr6FgjTwRJm7q+UtJAnBMQF+836qXykflkZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T17:27:12Z"
    mac: ENC[AES256_GCM,data:28vOjk/2gejIZLNDwK/50rV67gUDated+X+dCXs4Q/feopyx74LtkWbOoyi7t5hfP9Ok3YbKi/pwQIDHFdBx51d7W5E+M8vnSUW0HjDgKshV5NRhlzOxKwoDxA4hLTv+mJ+O+2iuyv4JoPPkgib/TLJddXVnrP+l/al+gL0Z1pU=,iv:NE7ShLee2oKQovZMGHukAlO2D4JYZiQ2Qkj+ugibvFY=,tag:c+xul6wsfUvpqeP0gUsJIw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
