log:
    level_unencrypted: info
    job_level_unencrypted: info
runner:
    file_unencrypted: /data/.runner
    capacity_unencrypted: 1
    timeout_unencrypted: 3h
    shutdown_timeout_unencrypted: 3h
    insecure_unencrypted: false
    fetch_timeout_unencrypted: 5s
    fetch_interval_unencrypted: 2s
    envs:
        CONTAINER_HOST: ENC[AES256_GCM,data:1XFn+dZUgZ9E6XpZKNhh+XaT8pZ2OCehvzMrEagXhHlUGzbqFXNaq5jd,iv:s3xLvf4Rp/T03fvLhENZmZqU0l8Torh9YWTpGGDqRoA=,tag:gCQDr3SqA8Dzv2sj1boQrw==,type:str]
        CONTAINER_SSHKEY_unencrypted: /etc/ssh/forgejo-runner-key
        SSH_OPTIONS_unencrypted: -o StrictHostKeyChecking=accept-new
        SOPS_AGE_KEY: ENC[AES256_GCM,data:w3HdlzUh7SAtpcNhN5kBKa7dFrXxyXQZOnCRgABFpNax/jxkNWnolfToIzoeqIy+M/NRO3mSizmAzL0Wo80EuNTDBVgHPRuP8aRHqVM8t1ja28TNNy9V+mE6SwigTYEdk0OjTS9MMPnZwvgDE3WTd/CJm6XwG9iKIAEw05OAnhLDKElEYXyapY9ubIHwFlkO+UKKO6MzF38Tf3+yS5BsgX/PPH73q5XWbhEdPElcaLsOaUINUI9oIg==,iv:rM7DshtFE67udBvn8HjpFspL77Rjf7Bz0G3iprBvC4Q=,tag:I3C39o8a90g4qLT3OwhdoQ==,type:str]
        DBUS_SESSION_BUS_ADDRESS: ENC[AES256_GCM,data:CIR4SKb3+DhGbxwlUp9q6JTHuoVaiq1NvS4aUA==,iv:zL8bu+ZPIT0rBlQLfSQK0SbjYXm2KIuglIc3DD54tp4=,tag:su8HkRyGG5+sy9RA1vcvOQ==,type:str]
    labels_unencrypted:
        - host:docker://localhost/forgejo-runner-job:latest
cache:
    enabled_unencrypted: false
container:
    network_unencrypted: ""
    enable_ipv6_unencrypted: false
    privileged_unencrypted: false
    docker_host_unencrypted: ssh://forgejo-runner@<host-ip-or-hostname>
    options_unencrypted: -v /run/user/1000/systemd/private:/run/user/1000/systemd/private -v /run/user/1000/bus:/run/user/1000/bus -v /home/lgomes/.config/containers/systemd:/root/.config/containers/systemd -v /home/lgomes/.config/systemd/user:/root/.config/systemd/user -v /home/lgomes/.ssh/forgejo-runner:/etc/ssh/forgejo-runner-key:ro
    valid_volumes_unencrypted:
        - /run/user/1000/systemd/private
        - /run/user/1000/bus
        - /home/lgomes/.config/containers/systemd
        - /home/lgomes/.config/systemd/user
        - /home/lgomes/.ssh/forgejo-runner
host:
    workdir_parent_unencrypted: /tmp
server:
    connections:
        forgejo:
            url: ENC[AES256_GCM,data:36eA+sBcoaYgnA5wzN6mcz43bX72vxnREpM=,iv:74hTvzinstjjTH0pPb35WjZlt4U6crAVQ6Oa89Ps9U0=,tag:9B3ZQFxXGub/H8ZqcXW/zA==,type:str]
            uuid: ENC[AES256_GCM,data:GExMRLFr92oRbyz/b8PLXJJ8LxgTZCsi8QBQMHwFnP1OJ34C,iv:aGgDgmwXUp+Ja3Ni03Do2Ut6jivJFZ2AtELNFyUeXUk=,tag:ChQN4VbenTFwzRKPQMsHUA==,type:str]
            token: ENC[AES256_GCM,data:fYebQRDgn2xe7wNdbhpG6W41SypcomT4nz9yYKv7J33tDe0zCU7ScA==,iv:2jl98pccEo0KAipBbyEreH+JS/hFMQgTSCOEgJjpyHo=,tag:SPCfhOpbZjw+fpILxCsMoQ==,type:str]
sops:
    age:
        - recipient: age197damvmzfln6huddgr6ujg8qjnmphsv5rumdu5xfh7c69dvsadasdpvce7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VTZKZFVsRHJmNnFVcWVV
            OWtLa0RqOWhjK3dHamV4MXpHRncwS1BOdDM0CkwyMXNja3ZyQ1huQXRmV2k4OElw
            c2U0ZFErVzQwbWlZNWlMbXZWVVVveVEKLS0tIE5rVzVIdGl3Nm0xT2FpQ0I5TjMy
            c29saXRkQWxiNE5CVkZkaVlZV3MzVkkKLHJNP8eUAKlFAx0gmPnYn5u56alyPz7U
            +i2jytZzAvuBRqTwSk/3BbkCIIQ3ZCLbCkLV350UxkjPgTPbYufO4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T07:46:58Z"
    mac: ENC[AES256_GCM,data:l1ueLbb0M5x+9JFPLaUu0T/6qYLHtZOu2w7i4a4F8qjrvSEBQCNU+C8H6ajtcrUGC26iBczVCx6f64ejgCwXSQL1EvdFSLrcSn8/RDOFP2zCLszwZw8Rwr7EoLEJSgkh/R2iBs/+u4XGGSy3aZDtBl2l8LIn+tk/hCtME9zf4X4=,iv:ichiDeGSEBcEykRSOYEHVkX93/gV2gejERF5+O1ejBw=,tag:HdU+2o3BI9/bFQ8STErWNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
