log:
    level: ENC[AES256_GCM,data:VLOKvg==,iv:ttQMZiLdTvuPF4Xje30Bf5W3m8rLBAh8HmBk7fg/NhY=,tag:qxpWSgI+62Lt/2HJLq9LDg==,type:str]
    job_level: ENC[AES256_GCM,data:JoGpRA==,iv:6JpRqI5QJ172iJN1xG0Iokiy0zNGaJS5i57GK46IoLk=,tag:EWv8eYD8Z7hAReJR2kOXWw==,type:str]
runner:
    file: ENC[AES256_GCM,data:TpShC6KlP9jRZSGzxQ==,iv:jiuRhcr/hYUCFghJGKjjFJ5x7VSFMj8bKBazstDHf70=,tag:em8Hlwuptj4G9vtiCeiW2g==,type:str]
    capacity: ENC[AES256_GCM,data:CQ==,iv:uyObXt3EOMCv9LME3C55M57DGTU13TxQoe5twJPy/K4=,tag:isVnPqY0UnY+NhFCEZ9WNQ==,type:int]
    timeout: ENC[AES256_GCM,data:VZY=,iv:rn40egJjJfuxHfAqhr2uiVQwNEo0AElpfKf48ofTfms=,tag:S/9/p0yPlH3s7fsn5jcS5A==,type:str]
    shutdown_timeout: ENC[AES256_GCM,data:6uE=,iv:FyinthzdZE7+FxH2tGXzp15vc4PmGoNaw1hecd0aA1M=,tag:0gTjZhlMhQTfM61hR3PLyw==,type:str]
    insecure: ENC[AES256_GCM,data:LilIl1s=,iv:jyP0oly1vt2cUR09FPeFrqur91NvpRELZUAC/80C8H4=,tag:z/Ao8cSJjHL2kLxePp3fbg==,type:bool]
    fetch_timeout: ENC[AES256_GCM,data:ooM=,iv:LTdO/WyMCO+ut0bq4M/pbpdQx+ITK7AFJ3iLxTkaqXE=,tag:hElksORjjSS6u7Y+vrd/lA==,type:str]
    fetch_interval: ENC[AES256_GCM,data:pLU=,iv:UB8NSIpWfqHmQ6mtx0JGVReRtY3UiOyE4jLToExZ8gE=,tag:65aQp7KuxC1lb5xQDpUbHg==,type:str]
    envs:
        CONTAINER_HOST: ENC[AES256_GCM,data:KIC+gANE3q8+UTJCef7cccoAg3gax//a1A==,iv:WySuh3OPas05vxb4UQ1dITfIs83t5422NfT3Ca660U8=,tag:4KOQ3kuFmSsWBplMhzfCPQ==,type:str]
        CONTAINER_SSHKEY: ENC[AES256_GCM,data:feZtWjICxYsxglWjShO7XFIVnYC6m8+s,iv:tgQxVYVNoFPKST1Uo3CsGwmMaZOFd8hoj2hZlogexMc=,tag:MmCivwQCr2zw+VvxbYRQYA==,type:str]
        SSH_OPTIONS: ENC[AES256_GCM,data:LjatwKV6klcr5RrNvtXr4u4Bez4asBvkNATra9PXu0iJRNs=,iv:EREdl1gKqVFGX6fbXEZWRWXnB/WbUwbcrrbTMv3Z7SM=,tag:UqIV6I52M4+IMdjIWn1b4Q==,type:str]
        SSH_PRIVATE_KEY: ENC[AES256_GCM,data:tF76C86YEC/fc9u9x7DqEJ51am/OySEtnwLn/3cY89tHthvgIwl0BwV5qH8QyOrzu4+lSfWb67pSksJs9wQC5NImId7qF0acFWkrqURZXpowFliPr+pXSTQhftuSZoqnC7LrH04bPAusBIVTsypD/T8Fy/cPEZ3FBRrImB5LysKYpd2dwvleG1kWKNIBcYmaQrEW0VnpNja3N+w0WR+xiUoKMQrSulo9o6z4gysBz1mzbMjZjndmiA0679hvpz9yy9HNKxg1XJUdhq1bJMIwvjS67u77fXNT6/geeIJ0jepkDqjj4kaRLGQjOYe0n6Q/LL7v+EPZi0uCdu+X2NjStOJ7BBhrnvfWezSmHR2jYRKapOHoBa0geD3Vql3DNIJr5umPP7nOznb8KRDJkP4BSyhdvVgOUDa3aC8i1X8q+7l0DylrtfsxSm+eJWsm3AsZCehbVsEOfAhVkDWkXxc97FZ/VvCgGpEVFr/IRaboU81SvmlLIL2VklzXkjzbrhXdfx2qVIom12Mchc/vt5I=,iv:yj7y/+VzdJ6SPwA/ixv6AJCjpbpCGjto3RqIFmvoOcQ=,tag:f6L+PQX4dOxp+dcmz6V2eA==,type:str]
        SOPS_AGE_KEY: ENC[AES256_GCM,data:lLfnR0YFDrOUEH4fJ781sdWU0gQ7oGjHukuWuBf45ff220oBOFlQLUdmecZ0rviERkATFl0U98Rk4idDBSAiQ+FWPWjH98cwSBz4UfhODrkA08Ey0tlwbD3cyHJ3uR7g5V2r3DSyvENsjI/IgS46RuxN39/vWmr863sRdPBjhxZC27ThO4ltV1Hzwf5Q8AL5ctKwcf4OChj60boqDlFMWMaHSj6+SFhV29qfeoAzuPHpQUSA/vki,iv:k9XNc5z4ILmTOOHlHl8llnjdfzze5V7zD7v64EYlLVo=,tag:Zxk74jKj0Wf/GBlvdTewaA==,type:str]
        DBUS_SESSION_BUS_ADDRESS: ENC[AES256_GCM,data:YgeK39L41PQjGCNb4Aa5eafb8c2TZX+2GnW+tA==,iv:b2y83gdy4YJp5wIAkSOE7VU3ABBzxBDpXiKtS8p/eng=,tag:KHj4GG43KBiIkmaBBA6M6A==,type:str]
    labels:
        - ENC[AES256_GCM,data:NIraInkKl/9fzx/ySf0dns8vAwnmpEujBcB9qQiuFrVaK5lSOgsBh111pF/HeIQcqg==,iv:DbtJXcqjqXRFwkobRkNx6I9S11AqPHNWXC+GjBkIL8g=,tag:lxQQbaVOf9JP/jDU8472kQ==,type:str]
cache:
    enabled: ENC[AES256_GCM,data:e3DD3eo=,iv:HlKxD2sJIUKsRoQfZPF/VRjcnD6HjWkb4fSCGorOs/I=,tag:mo8bsco7OylWQNr4siKrOw==,type:bool]
container:
    network: ENC[AES256_GCM,data:kkbNlEaRkuV+HdBS/Ta5ww==,iv:XyNFfRDy296SEYdxSSvDToqHxEMqR16Xu5SkIX1Ot/A=,tag:ennEm63HyJjVcWbpYQwsHA==,type:str]
    enable_ipv6: ENC[AES256_GCM,data:f266Fu8=,iv:6af7pn8rxgnhkQfCVqBhvqXe5hs7Gv75w8LAcowrY8o=,tag:5/U2wLXrhigF1fmBmLrjlg==,type:bool]
    privileged: ENC[AES256_GCM,data:OCJwOvg=,iv:nRZPyWtALzuR+j62xxZRMMssQ5Cp+YqfGP5AaPval5c=,tag:3kXszgFD0KD7xbJSSNHKlw==,type:bool]
    docker_host: ""
    options: ENC[AES256_GCM,data:2Zsryc4r7l0Wqnm2f9USdjIlBf7uwiGaK9V2X6NvTk9pm32dgincB480QyglrO1V8ThCfIajirYDPCb0+2rHpminactSskxK1NceRruh7pfdipIM7FiMQ/h/7udlIWmydb4d1n3XNZobTaJbh575/f0UrwfJlY6mq5V0Sdr5waWHlh1KL2EPbV/vrsIhE9FGMhjdaEkHI1nn++6sV465zCsFPBFPi1bSYDQGopzrJVq1wEJi8ih+uYaXiVTVOtyUQkDvoI+yLvkIsv3swaz7l1QvTPPO7GzizQb75Rk8RPmLf0yciW7xzK+3859kj2VIYv30gq0=,iv:zHF3ywcwFw0U+GLP47VHv7dUzrCEx50+3abNlDXP3Q8=,tag:oJpxZGSMrdgJjK/k7/en4Q==,type:str]
    valid_volumes:
        - ENC[AES256_GCM,data:oxSs2jiyGEP/Y1wAAQ7fOmjO7T5R9E3NBKrubtAV,iv:2AJVM6tmLLOYV+i08WsDdV7Z5j59avhY3kFVLYsr3mA=,tag:5qzVaX8tN85E/k5Xk3DjBQ==,type:str]
        - ENC[AES256_GCM,data:MbyrpyvhT/fdUl3lHIYjMOXF,iv:3oByvrt0HSi36OKhz8MQH31ulrIJmE34Svqev+zgMgw=,tag:8tvol3teuvKcButAvw3ISA==,type:str]
        - ENC[AES256_GCM,data:BEkUTHsx/LV4bGc++kfE9PT6jyh1cNWSH8pAek8b8nYXC84AAqmx,iv:0Xj6uwV2/V0+vY39h60BWIkLkiE7FgLF0Wfp2d5SRV8=,tag:8vDJR6lWgH/giPbPUqAcPw==,type:str]
        - ENC[AES256_GCM,data:1EANRpYnrGwiTdC4lBJBnExUj4DaPzlfFENCUpv3FG7C,iv:JIzWkLNO7sbiwhZJU0FLsxjYG0qwRtAexBWh1eWf7Fc=,tag:eRSj6X1J4UYqmKKkRNXT6w==,type:str]
host:
    workdir_parent: ENC[AES256_GCM,data:f1JB+Q==,iv:UvrR7wg7JxuCpAZciil68LvNlxDB9fcB5sNNN5xGIi0=,tag:NkXI99ZGaeDzYnUBzPtzmQ==,type:str]
server:
    connections:
        forgejo:
            url: ENC[AES256_GCM,data:LRqd/f8cvo90/cFB0eion/bvlJbVlPq8j2Q=,iv:5j/mgWdkqlWd6gF5y4DVbVMSYOLa5l5gny1g+n4RgWI=,tag:KmTsm50Im/0Rhf9fg5AztA==,type:str]
            uuid: ENC[AES256_GCM,data:kq7VsplM4Zf1tTxGGBY1j/45HT3RkzL6Qe9cNfTQyZgdqrBg,iv:vJ4GuIwEzDUcjxmDlDsVhxEdJtWhCFlRGnb3CGxjJMw=,tag:3oWmAktNgXGCDr5jiGoUDQ==,type:str]
            token: ENC[AES256_GCM,data:fALFbJ0c1CkSQXytDUvtpUKwaOBj3xmZFy8CfrdCk5zHRztJxbhS4w==,iv:PV7lHur3rEvX3XXN30j6ht77V7jhZ9R7ybXdAp9JVyU=,tag:4EyJIUvfFzL99AESxWLDDA==,type:str]
sops:
    age:
        - recipient: age197damvmzfln6huddgr6ujg8qjnmphsv5rumdu5xfh7c69dvsadasdpvce7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEY0ZTb2xPb044ZkFpN3hY
            ci9iTmZwOUcvZEF5a2FLNVFEUThFSWRNZ25nCmprVlkwSlBKL0VGbU5YQis5SlJs
            bFNFSVQwcm9jS3JCQld2RGN5SVNDNDQKLS0tIEhUOEJhTGRQeDY1bDd3d1NrNTZ0
            YUlRa0ZlR0txVzFFek8xaFBpMkpEenMKdj7Nd8TpQ3Nmf0YH8+AwR8srrhCM+BtO
            KRQZOCHm7FUiUsJCrCKcBiRK0hOqCAKDR7G3zIXQBo5y+pnfcCBPyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T08:30:46Z"
    mac: ENC[AES256_GCM,data:Q/vmaC4b2I1rSfC2pxirsIHMmgDOzVou2/jaznSuRRVJwtM1KbxagYvp4P6z0EU/WbDfUWovWTrul4HBVqgORJ9IeB2wXb58sdqckHjmudayyftFtJtg6YnyVnN03Q2BU3yh0u8bQVohfAbaUAILPiEsRDhJzVQNoDrCRqyee0Q=,iv:U887OIn9BTvrhvEmtgdt2RYwWQU47ZUOqy9/XxNGYew=,tag:nlFC/pXQYDcl9po9s5SRjA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
