FROM lscr.io/linuxserver/transmission:4.0.6

RUN apk add --no-cache curl && \
    mkdir -p /webui && \
    curl -o- -sL https://github.com/johman10/flood-for-transmission/releases/download/v1.0.1/flood-for-transmission.tar.gz | tar xzf - -C /webui && \
    apk del curl
